### ISSUE TITLE
t.Timestamps() args

### ISSUE THREAD

**Issue by mkungla** [gobuffalo/fizz#100]
Wold be nice to set args for `t.Timestamps()`

e.g.

`t.Timestamps("created_at", "updated_at", "deleted_at", "last_action_at")` etc.

**Comment by sio4** [comment]
How about using `t.Timestamp(string)` which is currently supported? Your example can be archived with the following:

```
t.Timestamps()
t.Timestamp("deleted_at")
t.Timestamp("last_action_at")
```

I am going to close this issue for now, but please feel free to reopen it if you have any further suggestion or experiences can be shared with us.

**Comment by mkungla** [comment]
@sio4 sound good it can be closed indeed, not sure was that there two years ago.

**Comment by sio4** [comment]
Yeah, sorry for the too late response. :-)
