### ISSUE TITLE
Add support for genji - A pure golang sql db

### ISSUE THREAD

**Issue by gedw99** [gobuffalo/fizz#103]
https://github.com/genjidb/genji

It’s very fast due to being embedded.
Has indexes
Has inner joins

Also you can get the DDL via dump to compare DDL in order to write a migration.

It also supports subscription like CDC style patterns and streaming backups and restores.

Been bullet proof in benchmarks where I hit it with 10 k concurrent gets and sets whilst doing streaming backup every 10 seconds.

**Comment by sio4** [comment]
Not sure if the core buffalo team has enough bandwidth to work on it, but PRs are always welcome!
