### ISSUE TITLE
Disable id and timestamps

### ISSUE THREAD

**Issue by RKelln** [gobuffalo/fizz#2]
I'm having trouble creating a relation table that doesn't have a primary key or timestamps:

Each game has players:
```
create_table("players_games") {
   	t.DisableTimestamps()
	t.Column("game_id", "uuid", {})
	t.Column("player_id", "uuid", {})
	t.ForeignKey("game_id", {"games": ["id"]}, {})
	t.ForeignKey("player_id", {"players": ["id"]}, {})
}
```
This panics: `panic: assignment to entry in nil map`  So I guess I'm using `DisableTimestamps()` incorrectly?

How do you set the options? Would be nice to have an option to disable the auto-id generation too.

Thanks!

**Comment by RKelln** [comment]
Looks like not having an id breaks expectations in gobuffalo so I'm using this currently and it is working (for postgres):
```
sql("CREATE TABLE player_games (
   id BIGSERIAL PRIMARY KEY,
   game_id uuid NOT NULL, 
   player_id uuid NOT NULL,
   FOREIGN KEY (game_id) REFERENCES games(id), 
   FOREIGN KEY (player_id) REFERENCES players(id),
   UNIQUE (game_id, player_id));")
```

**Comment by markbates** [comment]
@RKelln gobuffalo/pop requires an `id` so work needs to be done there to enable that as we can't break existing migrations.

I've opened a PR to fix the `t.Disabletamps` issue though. That should be merged shortly.
