### ISSUE TITLE
Use proper shell splitting for Exec

### ISSUE THREAD

**Issue by eugene-eeo** [gobuffalo/fizz#23]
Hi, I didn't see a similar issue created so I thought I should file one to find out what the rationale behind  that was (just using `strings.Split` instead of something more proper like [`go-shellquote`](https://github.com/kballard/go-shellquote)). Currently I run into issues if I'm trying to do

```javascript
exec("command --option='space separated string'")
```

**Comment by markbates** [comment]
No rationale, just a bug. :) PRs welcome! :)

**Comment by stanislas-m** [comment]
Fixed with #24.
