### ISSUE TITLE
rename_column() produce invalid SQL for mysql@5.7

### ISSUE THREAD

**Issue by boehmli** [gobuffalo/fizz#34]
Hey,
I'm not sure if this is a issue or my false configuration, in my opinion for mysql, the fizz command
rename_column("tablename", "oldcol", "newcol")
should produce something like:
ALTER TABLE \`tablename\` CHANGE \`oldcol\` \`newcol \` Type
but it produces:
ALTER TABLE \`tablename\` CHANGE \`oldcol newcol\` Type
which gives me an SQL Error near char(36) NOT NULL
Thanks for any help
EDIT: forget to escape the \`

**Comment by stanislas-m** [comment]
Hello, I don't understand your issue, can you provide more info? Is that about the `CHANGE` case?

**Comment by boehmli** [comment]
Thanks a lot for the reply!
Sry forget to escape the \´ so the issues are the \` around the table names

**Comment by stanislas-m** [comment]
What's your soda version? This bug was already fixed here: https://github.com/gobuffalo/fizz/pull/32

**Comment by boehmli** [comment]
Ah ok Updating Soda fixed it, thanks a lot!
