### ISSUE TITLE
Reference SQL files in sql()

### ISSUE THREAD

**Issue by ddoan** [gobuffalo/fizz#41]
So our use case is being able to manage SQL views in git.

Right now to edit a view, we have to create a migration and drop the view and replace it. That means, going back to a prior migration and finding the most recent version of that view, copy/pasting it over to the new migration and editing the new view. This is very error prone (what if I copied a view from 2 versions ago?) and creates a lot of duplicate mostly-the-same views in the migrations directory.

It would be great if we could have the `sql()` directive accept a path to a `.sql` file. That way, the file can be managed by source control, and edits to that file are only diffs.

**Comment by ddoan** [comment]
Here's my proposal.

```
diff --git a/raw_sql.go b/raw_sql.go
index eef1005..a0331ee 100644
--- a/raw_sql.go
+++ b/raw_sql.go
@@ -1,14 +1,23 @@
 package fizz

 import (
+       "io/ioutil"
        "strings"
 )

 func (f fizzer) RawSQL(sql string) {
+       var b []byte
+       var err error
+
+       if strings.HasPrefix(sql,"file://") {
+               b, err = ioutil.ReadFile(sql[7:])
+               sql = string(b)
+       }
+
        if !strings.HasSuffix(sql, ";") {
                sql += ";"
        }
-       f.add(sql, nil)
+       f.add(sql, err)
 }

 // Deprecated: use RawSQL instead.
```

**Comment by stanislas-m** [comment]
I understand your use case, but I'm against it. :) See, the whole point of the migrations is to prevent any change to the patches for the time they are applied. If we allow to change the contents from outside the patch, two databases can be patched in a very different way, and that's really bad for your database integrity.
