### ISSUE TITLE
Escaping issue with foreign keys and postgres

### ISSUE THREAD

**Issue by seopei** [gobuffalo/fizz#53]
Hi,

If you add a foreign key in fizz 
```
t.ForeignKey("VUNr", {"vers_unternehmen": ["VUNr"]}, {"on_update": "cascade"})
```
you will get
```
FOREIGN KEY (VUNr) REFERENCES vers_unternehmen (VUNr) ON UPDATE cascade,
```
for postgresSQL. This will result into the error `pq: column "vunr" referenced in foreign key constraint does not exist`.

In order to use upper case characters with foreign keys you have to manually escape it:
```
t.ForeignKey("\"VUNr\"", {"vers_unternehmen": ["\"VUNr\""]}, {"on_update": "cascade"})
```

I think this is not by design, because `t.PrimaryKey(...)`, etc. does the necessary escaping.

Cheers, Sebastian

**Comment by stanislas-m** [comment]
Thanks! It should work fine now. :)
